/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    QrcodeScanner: (typeof import('./src/components/QrcodeScanner/index.vue'))['default']
    SvgIcon: (typeof import('./src/components/SvgIcon/index.vue'))['default']
  }
}
